language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 3mar7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 3mar7/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-581291666900'
  bucket_path: 'app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
